# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
#    services:
#      selenium:
#        image: selenium/standalone-chrome:4.0.0-beta-1-prerelease-20210210
#        ports:
#          - 4444:4444
#        volumes:
#          - /dev/shm:/dev/shm
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        pip install webdriver-manager
        pip install pytest
        pip install pytest-html
        pip install pytest-cov
        pip install pytest-xdist
        pip install coverage
        pip install pytest-cov
        
    - name: Prepare Selenium
      # https://github.com/marketplace/actions/setup-chromedriver
      uses: nanasess/setup-chromedriver@master
#    - name: Launch browser
#      run: |
#        google-chrome --version
#        export DISPLAY=:99
#        chromedriver --url-base=/wd/hub &
#        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional, disables headless mode
    
    - name: Test marketplace action
      uses: simple-elf/allure-report-action@master
    
    - name: Test with pytest
#       for test coverage
      run: py.test tests/ -v -s --cov
#       run: py.test tests/ -v -s --cov
#        for html test coverage report
## run: py.test tests/ -v -s --cov --cov-report=html
# for code coverage report
#     - name: BrowserStack Test Coverage 
#       run : coverage run tests/test_browserStak.py
    
#     - name: BrowserStack coverage report
#       run : coverage report -m
      
#     - name: Chrome Test Coverage 
#       run : coverage run tests/test_chrome.py
    
#     - name: Chrome coverage report
#       run : coverage report -m
      
#     - name: FireFox Test Coverage 
#       run : coverage run tests/test_firefox.py
    
#     - name: FireFox coverage report
#       run : coverage report -m
        #      run: py.test tests/ -v -s --html=./reports/report.html --self-contained-html

